Pin HOL4 and remove CI sharding

diff --git a/.github/actions/setup-hol4/action.yml b/.github/actions/setup-hol4/action.yml
--- a/.github/actions/setup-hol4/action.yml
+++ b/.github/actions/setup-hol4/action.yml
@@ -21,8 +21,18 @@ runs:
     - name: Resolve HOL4 version
       id: version
       shell: bash
+      env:
+        HOL4_REF: ${{ inputs.hol4-ref }}
       run: |
-        rev=$(git ls-remote https://github.com/HOL-Theorem-Prover/HOL.git ${{ inputs.hol4-ref }} | cut -f1)
+        if [[ "$HOL4_REF" =~ ^[0-9a-fA-F]{40}$ ]]; then
+          rev="$HOL4_REF"
+        else
+          rev=$(git ls-remote https://github.com/HOL-Theorem-Prover/HOL.git "$HOL4_REF" | cut -f1)
+        fi
+        if [[ -z "$rev" ]]; then
+          echo "Could not resolve HOL4 ref: $HOL4_REF" >&2
+          exit 1
+        fi
         echo "hol4-rev=$rev" >> "$GITHUB_OUTPUT"
 
     - name: Cache HOL4
@@ -35,9 +45,12 @@ runs:
     - name: Build HOL4
       if: steps.cache-hol4.outputs.cache-hit != 'true'
       shell: bash
+      env:
+        HOL4_REV: ${{ steps.version.outputs.hol4-rev }}
       run: |
-        git clone -b "${{ inputs.hol4-ref }}" https://github.com/HOL-Theorem-Prover/HOL.git ~/HOL
+        git clone https://github.com/HOL-Theorem-Prover/HOL.git ~/HOL
         cd ~/HOL
+        git checkout --detach "$HOL4_REV"
         poly < tools/smart-configure.sml
         bin/build
 
